name: Deploy to My website
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ftp://files.000webhost.com:21/public_html
          user: lojatroc
          password: ${{ secrets.FTP_PASSWORD }}
          delete: "false"